packages: 
- openjdk-8-jre
- jenkins 

jenkins_signing_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key

jenkins_apt_repo: deb https://pkg.jenkins.io/debian-stable binary/

jenkins_pwd_path: /var/lib/jenkins/secrets/initialAdminPassword