- hosts: linux
  vars:
    certbot_package: "python3-certbot-nginx"
    certbot_plugin: "nginx"
  become: true
  become_method: sudo
  roles:
    - firewall
    - docker 
    - docker-compose
    - portainer
    - jenkins
    - install-nginx
    - letsencrypt
    - nginx-proxy
