- name: delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent 
  notify: restart nginx

- name: copy nginx site.conf
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled/{{ domain }}
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes