apt_http_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

docker_signing_url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

docker_repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable

docker_packages: 
  - docker-ce 
  - docker-ce-cli 
  - containerd.io
  - python3-pip