- name: Create git group
  group:
    name: git 
    state: present

- name: Create git user 
  user: 
    name: git 
    group: git
    comment: "Git Version Control"
    create_home: True 
    home: /home/git
    shell: /bin/bash
    password_lock: yes
    system: True

- name: Create the main gitea directory
  file:
    path: "{{ gitea_dest }}"
    state: directory
    owner: git
    group: git
    mode: '0777'

- name: Create gitea subdirectories {custom,data,log}
  file:
    path: "{{ gitea_subdirectories }}"
    state: directory
    owner: git 
    group: git   
    mode: '0777'

- name: Create temp directory for storing configs of the web installer
  file:
    path: "{{ gitea_temp_config_dir }}"
    state: directory
    owner: git 
    group: git 
    mode: '0777'

- name: Download gitea binary 
  get_url:
    url: "{{ gitea_binary_url }}"
    dest: "{{ gitea_dest }}/gitea"
    mode: '0777'

- name: Download gitea service file 
  get_url: 
    url: "{{ gitea_service_file_url }}"
    dest: "{{ gitea_service_file_dest }}/gitea.service"
    mode: '0777'

- name: Enable and start gitea service
  systemd:
    name: gitea.service 
    enabled: yes
    state: started
    daemon_reload: yes

- name: Place app.ini into the target directory 
  get_url: 
    url: "{{ app_ini_url }}"
    dest: "{{ app_ini_dest }}/app.ini"
    force: yes

- name: Reload the newly added app.ini config file 
  systemd:
    name: gitea.service 
    state: restarted