---
- name: Set timezone to Asia/Jakarta
  community.general.timezone:
    name: Asia/Jakarta

- name: Enabling UFW, allowing all traffic
  community.general.ufw:
    state: enabled
    policy: allow

- name: Set logging
  community.general.ufw:
    logging: 'on'